=== jfourmond/Graphe-Et-Ontologies/Ontologies/index327.dtd
<!ELEMENT IndexSource (ENTREE*) >
<!ELEMENT ENTREE (RELATION+, RENVOIS) >
<!ELEMENT RELATION (LIEN*) >
<!ELEMENT LIEN (#PCDATA) >
<!ELEMENT RENVOIS (LIEN*) >


<!ATTLIST IndexSource corpus CDATA #IMPLIED >
<!ATTLIST ENTREE id			CDATA	#REQUIRED
				 terme		CDATA 	#REQUIRED
				 validite 	CDATA 	#REQUIRED >
<!ATTLIST RELATION	nom		CDATA	#REQUIRED >

=== jfourmond/Graphe-Et-Ontologies/Ontologies/Index327.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>

<!DOCTYPE IndexSource SYSTEM "index327.dtd" >

<IndexSource corpus="htl.seq">

<ENTREE  terme =  "abc�s" validite = "Neutre"  id="1">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>abc�s proth�tique</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abc�s proth�tique" validite = "Neutre"  id="2">
   <RELATION nom="Tete">
          <LIEN>abc�s</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>abc�s</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MENSUITE_0_p1430-1</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abim�" validite = "Neutre"  id="3">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MENSUITE_0_p1115-4</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "ablation" validite = "Neutre"  id="4">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>ablation de le D�silet</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "ablation de le D�silet" validite = "Neutre"  id="5">
   <RELATION nom="Tete">
          <LIEN>ablation</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>ablation</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MENSUITE_0_p2232-1</LIEN>
          <LIEN>MENSUITE_0_p548-1</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abolition" validite = "Neutre"  id="6">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>abolition de le second bruit</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abolition de le second bruit" validite = "Neutre"  id="7">
   <RELATION nom="Tete">
          <LIEN>abolition</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>abolition</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MENSUITE_0_p1180-4</LIEN>
          <LIEN>MENSUITE_0_p1234-1</LIEN>
          <LIEN>MENSUITE_0_p743-3</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abordable chirurgicalement" validite = "Neutre"  id="8">
   <RELATION nom="Tete">
          <LIEN>abordable</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MENSUITE_0_p1483-1</LIEN>
          <LIEN>MENSUITE_0_p1486-2</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abouchement" validite = "Neutre"  id="9">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>abouchement de le vert�bral gauche</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abouchement de le vert�bral gauche" validite = "Neutre"  id="10">
   <RELATION nom="Tete">
          <LIEN>abouchement</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>abouchement</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MAPJACE11-5</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "Abrams" validite = "Neutre"  id="11">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>COR_4-3</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abrasion" validite = "Neutre"  id="12">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>abrasion de le onde r en territoire septal</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "abrasion de le onde r en territoire septal" validite = "Neutre"  id="13">
   <RELATION nom="Tete">
          <LIEN>abrasion</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>abrasion</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
          <LIEN>MENSUITE_0_p2363-2</LIEN>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "absence" validite = "Neutre"  id="14">
   <RELATION nom="Tete"  />
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>absence bilat�ral</LIEN>
          <LIEN>absence de alt�ration</LIEN>
          <LIEN>absence de anomalie de cin�tique segmentaire</LIEN>
          <LIEN>absence de argument</LIEN>
          <LIEN>absence de arythmie de perfusion</LIEN>
          <LIEN>absence de ath�romatose coronarien significatif</LIEN>
          <LIEN>absence de ath�roscl�rose significatif</LIEN>
          <LIEN>absence de cardiom�galie</LIEN>
          <LIEN>absence de dysfonction proth�tique notable</LIEN>
          <LIEN>absence de d�fect transitoire</LIEN>
          <LIEN>absence de fixation</LIEN>
          <LIEN>absence de infarctus important apical</LIEN>
          <LIEN>absence de insuffisance r�nal</LIEN>
          <LIEN>absence de isch�mie</LIEN>
          <LIEN>absence de leucocyturie</LIEN>
          <LIEN>absence de lit de aval abordable</LIEN>
          <LIEN>absence de l�sion significatif</LIEN>
          <LIEN>absence de modification important</LIEN>
          <LIEN>absence de mouvement</LIEN>
          <LIEN>absence de onde r initial</LIEN>
          <LIEN>absence de palpitation cardiaque</LIEN>
          <LIEN>absence de pathologie associ�</LIEN>
          <LIEN>absence de potentiel tardif</LIEN>
          <LIEN>absence de progression</LIEN>
          <LIEN>absence de restenose</LIEN>
          <LIEN>absence de r�cidive angineux</LIEN>
          <LIEN>absence de r�ponse</LIEN>
          <LIEN>absence de signe de defaillance cardiaque</LIEN>
          <LIEN>absence de st�nose</LIEN>
          <LIEN>absence de syndrome grippal</LIEN>
          <LIEN>absence de trouble</LIEN>
          <LIEN>absence de �l�vation</LIEN>
          <LIEN>absence total</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE"  />
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "absence bilat�ral" validite = "Neutre"  id="15">
   <RELATION nom="Tete">
          <LIEN>absence</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE">
          <LIEN></LIEN>
          <LIEN>absence bilat�ral de le pouls poplit�</LIEN>
   </RELATION>
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>absence</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
   <RELATION nom="SYNONYMIE"  />
   <RELATION nom="SPECIALISATION"  />
   <RELATION nom="DERIVES"  />
   <RELATION nom="AUTRE"  />
   <RENVOIS>
     </RENVOIS>
 </ENTREE>

<ENTREE  terme =  "absence bilat�ral de le pouls poplit�" validite = "Neutre"  id="16">
   <RELATION nom="Tete">
          <LIEN>absence</LIEN>
   </RELATION>
   <RELATION nom="HYPERONYMIE"  />
   <RELATION nom="MERONYMIE">
          <LIEN></LIEN>
          <LIEN>absence bilat�ral</LIEN>
   </RELATION>
   <RELATION nom="VARIANTE TERMINOLOGIQUE"  />
